name: Firebase Hosting Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v4

      # Configura o Node.js para a versão necessária
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ou a versão que você está utilizando

      # Instala as dependências
      - name: Install dependencies
        run: |
          npm install

      # Rodar o build (se necessário, caso tenha um script de build configurado)
      - name: Run build
        run: |
          npm run build

      # Fazer login no Firebase
      - name: Firebase login
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLITZ_BA5AE }}" > firebase-service-account.json
          firebase use --add
          firebase deploy --token ${{ secrets.FIREBASE_AUTH_TOKEN }} --only hosting

      # Optional: Limpar os arquivos de autenticação
      - name: Clean up
        run: |
          rm firebase-service-account.json

